project_id = "diieheagpzlqatqpzjua"

[functions.secure-payment]
verify_jwt = true

[functions.secure-paytech]
verify_jwt = true

[functions.secure-paytech-status]
verify_jwt = true

[functions.share-prescription]
verify_jwt = true

[functions.process-reminders]
verify_jwt = false

[functions.verify-payment]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.approve-doctor-application]
verify_jwt = true

[functions.reject-doctor-application]
verify_jwt = true